# Generated by Kavia CodeGen

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


def seed_initial_data(apps, schema_editor):
    # Optional: no default data for now
    pass


def unseed_initial_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("ingredients", models.TextField(help_text="List ingredients, one per line or JSON-like text.")),
                ("steps", models.TextField(help_text="Cooking steps and instructions.")),
                ("image_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recipes", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="recipe", index=models.Index(fields=["title"], name="api_recipe_title_c3a2c1_idx")),
        migrations.AddIndex(model_name="recipe", index=models.Index(fields=["created_at"], name="api_recipe_create_09c0a5_idx")),
        migrations.RunPython(seed_initial_data, unseed_initial_data),
    ]
